version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 2s
      retries: 5
      start_period: 2s
    networks:
      - modulo4

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9092:9092"
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1
      interval: 2s
      retries: 5
      start_period: 2s
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: BROKER://kafka1:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:19092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 300
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - modulo4

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9093:9093"
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9093 || exit 1
      interval: 2s
      retries: 5
      start_period: 2s
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: BROKER://kafka2:19093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:19093,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 300
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - modulo4

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - modulo4
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:19092,kafka2:19093"

  consumer1:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    networks:
      - modulo4
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:19092,kafka2:19093"
      KAFKA_GROUP_ID: "fila-processamento-group"

  consumer2:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    networks:
      - modulo4
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:19092,kafka2:19093"
      KAFKA_GROUP_ID: "fila-processamento-group"

networks:
  modulo4:
    driver: bridge