name: Build (Multi-module Maven)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-producer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Config
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          
      - name: Build Producer
        run: mvn -f producer/pom.xml -B -e -ntp clean package
        
      - name: Build Consumer
        run: mvn -f consumer/pom.xml -B -e -ntp clean package
